version: '3.8'

services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command: node main.js
    ports:
      - "3000-3003:3000-3003" # see the view from the camera mounted on your bot head: http://localhost:3000/

  viaproxy: #use this service to connect to an unsupported minecraft server versions. more info: ./services/viaproxy/README.md
    image: ghcr.io/viaversion/viaproxy:latest
    volumes:
      - ./services/viaproxy:/app/run
    ports:
      - "25568:25568"
    profiles:
      - viaproxy

  openai_agent:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./services/openai_agent:/app
    command: bash -c "pip install uv && uv pip install -e . && python agent_server.py"
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    profiles:
      - openai_agent